# HTTP Server
server:
  port: ${PORT:9291}   # HTTP port

# Spring properties
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: customer
          uri: lb://CUSTOMER
          predicates:
          - Path=/customer/**

        - id: user
          uri: lb://USER
          predicates:
          - Path=/user/**

        - id: bancos
          uri: lb://BANCOS
          predicates:
          - Path=/bancos/**

        - id: tmp-repo-folders
          uri: lb://CATALOG
          predicates:
          - Path=/tmp-repo-folders/**

        - id: impi-address
          uri: lb://CATALOG
          predicates:
          - Path=/impi-address/**

        - id: catalog-generics
          uri: lb://CATALOG
          predicates:
          - Path=/catalog-generics/**

        - id: jobareas-procedurephases
          uri: lb://CATALOG
          predicates:
          - Path=/jobareas-procedurephases/**

        - id: job-areas
          uri: lb://CATALOG
          predicates:
          - Path=/job-areas/**

        - id: jobareas-referencetypes
          uri: lb://CATALOG
          predicates:
          - Path=/jobareas-referencetypes/**

        - id: languages
          uri: lb://CATALOG
          predicates:
          - Path=/languages/**

        - id: procedure-phases
          uri: lb://CATALOG
          predicates:
          - Path=/procedure-phases/**

        - id: reference-types
          uri: lb://CATALOG
          predicates:
          - Path=/reference-types/**

        - id: permission-levels
          uri: lb://CATALOG
          predicates:
          - Path=/permission-levels/**
          
        - id: impi-subaddress
          uri: lb://CATALOG
          predicates:
          - Path=/impi-subaddress/**
          
          - id: coordinations
          uri: lb://CATALOG
          predicates:
          - Path=/coordinations/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

# Discovery Server Access
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
